apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: features
  labels:
    name: features
spec:
  replicas: 1
  selector:
    matchLabels:
      name: features

  template:
    metadata:
      labels:
        name: features
    spec:
      containers:
      - image: us.gcr.io/honestcodecloud/features:$CI_PIPELINE_ID
        name: features
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: DB_URI
          value: "mongodb://$DB_USER_PRO:$DB_PASSWORD_PRO@ds015975-a0.mlab.com:15975,ds015975-a1.mlab.com:15975/honestcode-pro-rs?replicaSet=rs-ds015975&socketTimeoutMS=30000&slaveOk=false"
        - name: PAPERTRAIL_HOST
          value: "logs4.papertrailapp.com"
        - name: PAPERTRAIL_PORT
          value: "33942"
        - name: GECKO_APIKEY
          value: "a2a3a0718d3e36b22c80e9c76bde9968"
        - name: GECKO_WIDGET_STEP_COUNT
          value: "https://push.geckoboard.com/v1/send/121408-2d0bec10-2ba9-0134-70e1-22000b5980c2"
