apiVersion: v1
kind: Service
metadata:
  name: features
  labels:
    name: features
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    name: features
