# Automatically generated by Honest Code
# Do not edit this file as it will be overwritten

Feature: Create new feature
  As a api client
  I want to be able to create new features

  Scenario: Create new feature
    When I request creation of new feature with following data
      | name      | blueprint   | context   | goal   | tags      |
      | feature 1 | blueprint 1 | context 1 | goal 1 | tag1,tag2 |
    Then the response status code is 201
    And the response body has a "id" field

  Scenario: Created feature has correct information
    When I request creation of new feature with following data
      | name      | blueprint   | context      | goal                   | tags      |
      | feature 1 | blueprint 1 | as a context | I want to score a goal | tag1,tag2 |
    And I request to find all features of blueprint "blueprint 1"
    Then the response status code is 200
    And the response body has a "items" field with a list of 1 items
    And the response body item 0 has a "id" field
    And the response body item 0 has a "name" field with "feature 1" value
    And the response body item 0 has a "tags" field with 2 items
